from __future__ import annotations

import ast
import io
import re
import tokenize
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "trustport"

FORBIDDEN = (
    "reproduction of",
    "based on the paper",
    "re-implementation",
    "following the authors",
    "as described by",
    "generated by",
    "ai-assisted",
    "skeleton",
    "placeholder",
    "todo from paper",
    "cutting-edge",
    "seamlessly",
    "leveraging",
    "utilize",
    "delve",
    "holistic",
    "meticulously",
    "it's worth noting",
    "in conclusion",
)

EMOJI = re.compile(
    "[\U0001f000-\U0001faff\U00002600-\U000027bf\U0001f1e6-\U0001f1ff\U00002190-\U000021ff]"
)


def _python_files() -> list[Path]:
    return sorted(PACKAGE.rglob("*.py"))


def test_no_comments() -> None:
    for path in _python_files():
        source = path.read_text(encoding="utf-8")
        for token in tokenize.generate_tokens(io.StringIO(source).readline):
            assert token.type != tokenize.COMMENT, f"comment found in {path}"


def test_no_docstrings() -> None:
    for path in _python_files():
        tree = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(tree):
            if isinstance(node, ast.Module | ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef):
                assert ast.get_docstring(node) is None, f"docstring found in {path}"


def test_no_forbidden_phrases() -> None:
    targets = _python_files() + [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        if not path.exists():
            continue
        lowered = path.read_text(encoding="utf-8").lower()
        for phrase in FORBIDDEN:
            assert phrase not in lowered, f"forbidden phrase {phrase!r} in {path}"


def test_no_emoji() -> None:
    targets = _python_files() + [ROOT / "README.md", ROOT / "Makefile"]
    for path in targets:
        if not path.exists():
            continue
        assert not EMOJI.search(path.read_text(encoding="utf-8")), f"emoji in {path}"
