name: trustport
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.2
  - numpy>=1.26
  - scipy>=1.11
  - pip:
      - omegaconf>=2.3
      - simple-parsing>=0.1.6
      - rank-bm25>=0.2.2
      - typing-extensions>=4.9
